### ISSUE TITLE
Writing records as json instead of avro to topic

### ISSUE THREAD

**Issue by skynyrd** [jcustenborder/kafka-connect-rabbitmq#17]
Hi, thanks for your community support.

I use the connector for reading from RabbitMQ and writing to Kafka.
Everything perfectly works, however, I want to get messages as json in the Kafka topic instead of Avro.

This is how I initialize the connector:
`connect-distributed config/worker.qa.properties`

and this is the `worker.qa.properties`:

```
bootstrap.servers=192.168.57.12:9092,192.168.57.12:19092,192.168.57.12:29092

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
plugin.path=/etc/kafka-connect/jars
consumer.max.poll.records=5000

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true

group.id=mordorconnectcluster-qa
config.storage.topic=config-storage-qa
offset.storage.topic=offset-storage-qa
status.storage.topic=status-storage-qa
```

After that, I call connect http api for creating the connector.

What should I do for the json message formatting? Thanks.

**Comment by jcustenborder** [comment]
That's all you need to do. The connector it's self doesn't handle any formatting. It just delegates the serialization to the converter. My test configs use avro. There is no requirement for it.

**Comment by psmod2** [comment]
@skynyrd - Thanks for the above - I was looking for that line `internal.key.converter.schemas.enable=false` 

One other thing now, when I look at the topic, I see the body is in Base64 - is there any configuration to get that decoded? Or is that something I need to do on my processing side?

Also, is there anyway to get only the body and ignore everything else?

Thanks.

(cc @jcustenborder in case you know)

**Comment by jcustenborder** [comment]
@psmod2 Never change the internal converter configuration. The configuration will be removed at some point in the near future.
