### ISSUE TITLE
Connector always writing to one partition in a topic

### ISSUE THREAD

**Issue by skynyrd** [jcustenborder/kafka-connect-rabbitmq#18]
Hi,

The connector always writing one partition in a topic even if a topic has multiple partitions.

I am modifying the connector to change the SourceRecordBuilder as the following discussion recommendation:
https://groups.google.com/forum/#!topic/confluent-platform/-gFyHonFXiA

**Comment by jcustenborder** [comment]
Hi @skynyrd! The connector uses the [message id](https://github.com/jcustenborder/kafka-connect-rabbitmq/blob/master/src/main/java/com/github/jcustenborder/kafka/connect/rabbitmq/MessageConverter.java#L281) from the message to generate a key. Take a look at what this value is. You can also look into using a transformation to change the key to something based on the data. If you still are having issue reopen this.

**Comment by maxtar** [comment]
@jcustenborder What I need todo if I no need to use message ID?
