### ISSUE TITLE
Build a jar file with all dependencies

### ISSUE THREAD

**Issue by DiegoReiriz** [jcustenborder/kafka-connect-rabbitmq#20]
Hello!

I want to know if you tought about building a fat jar version with all depencies needed bundled inside of the jar. That makes the deployment of a new connector more easier than deploy the jar without dependecies and have to  ensure yourself that your kafka server have all those dependencies.

Thx for your time!

**Comment by jcustenborder** [comment]
Thanks for the interest @DiegoReiriz. Due to licensing weirdnesses I will never be creating fat jars of my connectors. Take a look at the plugin isolation features that were added to connect in 0.11. This makes some of the deployment much easier.
