### ISSUE TITLE
Producer not flushing the Messages

### ISSUE THREAD

**Issue by mariojunior** [jcustenborder/kafka-connect-rabbitmq#21]
I'm getting the following Error Messages:

```
[2017-12-20 09:55:21,342] ERROR WorkerSourceTask{id=rabbitmq-0} Failed to flush, timed out while waiting for producer to flush outstanding 1 messages (org.apache.kafka.connect.runtime.WorkerSourceTask:328)

[2017-12-20 09:55:21,342] ERROR WorkerSourceTask{id=rabbitmq-0} Failed to commit offsets (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:111)
```

I can see my messages on RabbitMQ being consumed, but the 'ack' isn't sent to the RabbitMQ letting all messages as 'Unacked' state, which would mean the method  RabbitMQSourceTask.java:commitRecord(SourceRecord) at line 85 is never invoked.

My first guess was 'ha, ok.. the component is consuming from RabbitMQ but is not sending to Kafka because isn't reaching kafka:9092 address' but isn't the case once if I stop only the kafka container then the component gets a lot of errors about the Connection could not be established by the kafka producer.

Then, any clue/tip why the Worker Task isn't flushing my messages into Kafka?

Thanks.

**Comment by jcustenborder** [comment]
Hi @mariojunior,

Are you using my [config/connect-avro-docker.properties](https://github.com/jcustenborder/kafka-connect-rabbitmq/blob/master/config/connect-avro-docker.properties) as your configuration file? This file is specific to the docker environment that I use for testing. You should make sure that the [bootstrap.servers](https://github.com/jcustenborder/kafka-connect-rabbitmq/blob/master/config/connect-avro-docker.properties#L17) line is pointing to your kafka brokers. The connector consumes from RabbitMQ but once Kafka has actually written a message [commitRecord](https://github.com/jcustenborder/kafka-connect-rabbitmq/blob/master/src/main/java/com/github/jcustenborder/kafka/connect/rabbitmq/RabbitMQSourceTask.java#L85-L92) is called. I'm thinking that you are unable to connect to Kafka which is why this is never happening.

**Comment by mariojunior** [comment]
Hi, yeah... I'm using your docker properties, however, I had to change any 'kafka:9092' to 'localhost:9092' ... the same for schema-registry due to I'm running on Docker for macOS and although docker-composer bring up the services and link them correctly, docker doesn't map the DNS names correctly (i.e try "curl kafka:9092" it doesn't work, but if try "curl localhost:9092" works. The response is a "_Empty reply from server_") but considering I'm running all on the same machine 'localhost' did work and made them accessible.

If I let the containers running I can, in another terminal session, use the shell producer and consumer normally. Which tells me the kafka is running and is accessible, however, when I run your plugin, I get stuck on this problem (commitRecord is never called).

I've downloaded the Confluent Enterprise edition for demo, and placed your plugin inside the folders and - using the Confluent - I was able to see it running great, but in the open source edition it isn't... is that dependent somehow of the enterprise edition only?

By the way, hey bro... it's Christmas, go take a rest and enjoy the holiday. :) (not for me anymore, due to timezone, it's already 26/dec.)

Thanks.

**Comment by jcustenborder** [comment]
One thing to keep in mind with Kafka. A Kafka broker advertises it's hostname. If you connect with localhost:9092 that is only to get a view of what the cluster looks like. IE bootstrap. All network traffic from that point to the brokers will be by the hostname that it advertises. All nodes of a cluster must advertise a reachable hostname. In the case of the docker-compose.yml and config in this repo, it requires my mac to have the following in the `/etc/hosts` file. 

```
127.0.0.1 zookeeper
127.0.0.1 kafka
``` 

There is nothing specific to this connector that would cause it to only work with Enterprise.

**Comment by mariojunior** [comment]
Nice. It worked.
Maybe it worth to mention in the Readme file.
Also, I've done a little change in the connect-avro-docker.properties, where is:
`plugin.path=target/kafka-connect-target/usr/share/java`

the correct is:
`plugin.path=target/kafka-connect-target/usr/share/kafka-connect`

(or we may tell maven where to place the final build target path on the pom.xml).

Thank you very much dude, have a happy new year. 👍 
<img width="446" alt="screen shot 2017-12-27 at 1 17 13 pm" src="https://user-images.githubusercontent.com/444465/34366984-1710b946-eb09-11e7-925e-ead67115cac7.png">
