### ISSUE TITLE
How to use header value as partition key

### ISSUE THREAD

**Issue by monepic** [jcustenborder/kafka-connect-rabbitmq#22]
Hi @jcustenborder 

Thanks for the plugin!  

I'm new to Kafka/connect and I'm trying to work out which set of SMTs I'd need to apply in order to use an arbitrary RMQ header as the partition key

I've included an example message (as is spat out by `kafka-avro-console-consumer`) below; I'd like to use **mySpecialHeader** as the key.

I'd assumed the process to make that work would be 
1. __ValueToKey__ - copy the _basicProperties_ as the key
2. __ExtractField$Key__ - extract _basicProperties_
3. __ExtractField$Key__ - extract _headers_
4. __ExtractField$Key__ - extract _mySpecialHeader_

However step 4 fails with  
`org.apache.kafka.connect.errors.DataException: Only Struct objects supported for [field extraction], found: java.util.LinkedHashMap`

I'm not exactly sure how to resolve that, also the convoluted nature of this whole process makes me suspicious that I'm not approaching this problem the correct way.

Do you have any idea what I need to do to get it to work?

```
{
  "consumerTag": "amq.ctag-fDpfjCQfHKnwhRt4QUNeAQ",
  "envelope": {
    "deliveryTag": 91386,
    "isRedeliver": false,
    "exchange": {
      "string": "exchange.name"
    },
    "routingKey": {
      "string": "routing.key"
    }
  },
  "basicProperties": {
    "com.github.jcustenborder.kafka.connect.rabbitmq.BasicProperties": {
      "contentType": {
        "string": "text/plain"
      },
      "contentEncoding": {
        "string": "UTF-8"
      },
      "headers": {
        "mySpecialHeader": {
          "type": "string",
          "timestamp": null,
          "int8": null,
          "int16": null,
          "int32": null,
          "int64": null,
          "float32": null,
          "float64": null,
          "boolean": null,
          "string": {
            "string": "1234567.123456789012.ABCD"
          },
          "bytes": null
        },
      },
      "deliveryMode": {
        "int": 2
      },
      "priority": {
        "int": 0
      },
      "correlationId": null,
      "replyTo": null,
      "expiration": null,
      "messageId": null,
      "timestamp": null,
      "type": null,
      "userId": null,
      "appId": null
    }
  },
  "body": "Message body goes here"
}
```

**Comment by jcustenborder** [comment]
Hey @monepic!

Your use case made a lot of sense so I added a transformation to help do this. Can you take a look at the [ExtractHeader](https://github.com/jcustenborder/kafka-connect-rabbitmq#extractheaderkey) transformation? This will grab the value of a header and use it as the key. This will be stored as the type specified in the header. For example a header with a string value will be stored as a `string`, a header with a numeric value will be stored as the corresponding number type. IE `int32`, `int64`. One thing to keep in mind is this must stay consistent if you are using Avro. The Avro converter will be angered if you switch from a string header to an int header. Please give this a shot and let me know how this works for you. Reopen this if you need. 

J

**Comment by monepic** [comment]
Many thanks for this!  - It worked nicely.

I think in the README `connector.class` value may be a typo though?
`"connector.class": "com.github.jcustenborder.kafka.connect.rabbitmq.ExtractHeader$Value",`

**Comment by jcustenborder** [comment]
yea that shouldn't be there. The connector.class should be the connector. The transform class is the part you need. Part of the documentation is dynamically generated.
