### ISSUE TITLE
Does the internal key/value matter and what should they be?

### ISSUE THREAD

**Issue by psmod2** [jcustenborder/kafka-connect-rabbitmq#40]
Hi,

Does it matter what the:

```
internal.key.converter: "org.apache.kafka.connect.json.JsonConverter"
internal.value.converter: "org.apache.kafka.connect.json.JsonConverter"
```

should be?

And if so, what is the recommended converters I should be using?

I'm wanting to save JSON from RabbitMQ.

**Comment by jcustenborder** [comment]
internal means internal to kafka. Never change this. It will be removed in a later version of Apache Kafka.

**Comment by psmod2** [comment]
@jcustenborder - If i remove this from my configuration i get an error stating `internal.key.converter` required. So what should the default value be?
