### ISSUE TITLE
is it possible to write raw messages from RabbitMQ to a topic?

### ISSUE THREAD

**Issue by sragatsky** [jcustenborder/kafka-connect-rabbitmq#6]
im able to write amqp jsons into a topic eg:

`{"consumerTag":"amq.ctag-Qm63jsUITbKcDqbSIai_pg","envelope":{"deliveryTag":1,"isRedeliver":false,"exchange":"","routingKey":"test_adnymics_queue"},"basicProperties":{"contentType":null,"contentEncoding":null,"headers":{},"deliveryMode":1,"priority":null,"correlationId":null,"replyTo":null,"expiration":null,"messageId":null,"timestamp":null,"type":null,"userId":null,"appId":null},"body":"eyJ0ZXN0IjoidGVzdCJ9"}
`

Is it possible to write raw messages (the body?) that is received by Rabbit and read by the connector into a topic?
eg: `{"test_key": "test_val"}`

**Comment by jcustenborder** [comment]
@sragatsky I'm not sure what you are meaning here. The connector creates a body format that contains everything that is in the message. If for example you only want the body you could use a single message transform to just grab the body. I think [org.apache.kafka.connect.transforms.ExtractField$Value](https://kafka.apache.org/documentation/#connect_transforms) might do what you are looking for.

**Comment by jcustenborder** [comment]
I didn't hear back from you. If you're just wanting the body a Single Message Transform is your best path. That or using Kafka Streams.

**Comment by maxtar** [comment]
@jcustenborder We have the same trouble. May you explain which connector settings we need for saving rabbitmq message to kafka topic as is?

**Comment by vkasarekar** [comment]
yes, an example will be helpful.
