### ISSUE TITLE
NoSuchMethodError org.apache.kafka.connect.source.SourceRecord.<init>(...)

### ISSUE THREAD

**Issue by Yotamho** [jcustenborder/kafka-connect-rabbitmq#7]
Hello,
I am using kafka-connect-rabbitmq with kafka 0.10.0.0,
When calling RabbitMQSourceConnector, I get the following error:

`[2017-06-26 14:36:31,088] ERROR Consumer com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer@7b721966 (amq.ctag-rz_tCFPQsRVdhJg36VQh7g) method handleDelivery for channel AMQChannel(amqp://guest@10.6.22.44:5672/,1) threw an exception for channel AMQChannel(amqp://guest@10.6.22.44:5672/,1) (com.rabbitmq.client.impl.ForgivingExceptionHandler)
java.lang.NoSuchMethodError: org.apache.kafka.connect.source.SourceRecord.<init>(Ljava/util/Map;Ljava/util/Map;Ljava/lang/String;Ljava/lang/Integer;Lorg/apache/kafka/connect/data/Schema;Ljava/lang/Object;Lorg/apache/kafka/connect/data/Schema;Ljava/lang/Object;Ljava/lang/Long;)V
        at com.github.jcustenborder.kafka.connect.rabbitmq.SourceRecordBuilder.sourceRecord(SourceRecordBuilder.java:48)
        at com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer.handleDelivery(ConnectConsumer.java:70)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

I assumed that this error is caused by incompatibility between my kafka server (v0.10.0.0) and the kafka-client version (seems like v0.10.2.0-cp1).
then I tried to set a kafka-connect-parent pom file locally, and set the kafka.version property to 0.10.0.0
then I tried to build with maven and got similar error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project kafka-connect-rabbitmq: Compilation failure: Compilation failure:
[ERROR] /C:/Users/yotamh/IdeaProjects/kafka-connect-rabbitmq/src/main/java/com/github/jcustenborder/kafka/connect/rabbitmq/RabbitMQSourceTask.java:[84,3] method does not override or implement a method from a supertype
[ERROR] /C:/Users/yotamh/IdeaProjects/kafka-connect-rabbitmq/src/main/java/com/github/jcustenborder/kafka/connect/rabbitmq/SourceRecordBuilder.java:[39,12] no suitable constructor found for SourceRecord(com.google.common.collect.ImmutableMap<java.lang.String,java.lang.String>,com.google.common.collect.ImmutableMap<java.lang.String,java.lang.Long>,java.lang.String,<nulltype>,org.apache.kafka.connect.data.Schema,org.apache.kafka.connect.data.Struct,org.apache.kafka.connect.data.Schema,org.apache.kafka.connect.data.Struct,long)
[ERROR] constructor org.apache.kafka.connect.source.SourceRecord.SourceRecord(java.util.Map<java.lang.String,?>,java.util.Map<java.lang.String,?>,java.lang.String,java.lang.Integer,org.apache.kafka.connect.data.Schema,java.lang.Object) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor org.apache.kafka.connect.source.SourceRecord.SourceRecord(java.util.Map<java.lang.String,?>,java.util.Map<java.lang.String,?>,java.lang.String,org.apache.kafka.connect.data.Schema,java.lang.Object) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor org.apache.kafka.connect.source.SourceRecord.SourceRecord(java.util.Map<java.lang.String,?>,java.util.Map<java.lang.String,?>,java.lang.String,java.lang.Integer,org.apache.kafka.connect.data.Schema,java.lang.Object,org.apache.kafka.connect.data.Schema,java.lang.Object) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /C:/Users/yotamh/IdeaProjects/kafka-connect-rabbitmq/src/main/java/com/github/jcustenborder/kafka/connect/rabbitmq/RabbitMQSourceConnector.java:[63,3] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

Is the cause of the error indeed the incompatibility between the versions?
Is there any workaround / supporting version for kafka 0.10.0.0?
Thanks in advance

**Comment by jcustenborder** [comment]
Yes this is built against 10.2.x. That is a missing method in kafka. Your best bet would be to run a 10.2.x version of kafka connect.
